config/routes.rb
Truenorth::Application.routes.draw do
  resources :websites
   
	
  ErpBaseErpSvcs.mount_compass_ae_engines(self)

end

app/models/individual.rb
class Individual < ActiveRecord::Base
  validates :current_personal_title, :format => {:with => /^[a-zA-Z\.]{0,255}$/,allow_blank: true, message: "Only alphabets & dot symbol allowed."}
  validates :current_first_name, :format => {:with => /^[a-zA-Z\. ]{3,255}$/,allow_blank: false, message: "Only alphabets, space & dot symbol allowed."}
  validates :current_middle_name, :format => {:with => /^[a-zA-Z\. ]{0,255}$/,allow_blank: true, message: "Only alphabets, space & dot symbol allowed."}
  validates :current_last_name, :format => {:with => /^[a-zA-Z\. ]{1,255}$/,allow_blank: false, message: "Only alphabets, space & dot symbol allowed."}
  validates :current_suffix, :format => {:with => /^[a-zA-Z\. ]{0,255}$/,allow_blank: true, message: "Only alphabets, space & dot symbol allowed."}
  validates :current_nickname, :format => {:with => /^[a-zA-Z\ ]{0,255}$/,allow_blank: true, message: "Only alphabets, space allowed."}
  validates :current_passport_number, :format => {:with => /\A[0-9]{8,8}+\z/,allow_blank: true, message: "Only numbers allowed.Password length should be 8 character length"}
  validates :total_years_work_experience, :format => {:with => /\A[0-9]{0,2}+\z/,allow_blank: true, message: "Invalid work experience. Only numbers allowed."}
  validates :marital_status, :format => {:with => /^[a-zA-Z]{0,1}$/,allow_blank: true, message: "Only alphabets allowed. Maximum length should be 1"}
  validates :social_security_number, :format => {:with => /^\b[0-9]{3}-[0-9]{2}-[0-9]{4}\b/,allow_blank: true, message: "Invalid SSS number. Only numbers & - allowed."}
end

app/models/website.rb
class Website < ActiveRecord::Base
  attr_accessible :name, :title, :subtitle
  validates :name,  :presence => true,:length => { :minimum => 5 }
  validates :title, :presence => true

end

app/models/website_old.rb
class Websites < ActiveRecord::Base
  attr_accessible :name, :title, :subtitle
end

app/controllers/_website_controller.rb
class WebsiteController < ApplicationController
  def index
    @websites = Website.all

    respond_to do |format|
      format.html  # index.html.erb
      format.json  { render :json => @websites }
    end
  end
  def new
  end
end
#module ErpApp
#  module Desktop
#    module ExampleApp
#      class WebsiteController < ::ErpApp::Desktop::BaseController
#      def index
#	end
#      end
#    end #ExampleApp
#  end #Desktop
#end #ErpApp

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/erp_app/desktop/example_app/base_controller.rb
module ErpApp
  module Desktop
    module ExampleApp
      class BaseController < ::ErpApp::Desktop::BaseController
      
      end
    end #ExampleApp
  end #Desktop
end #ErpApp

app/controllers/erp_app/desktop/ig/base_controller.rb
module ErpApp
  module Desktop
    module Ig
      class BaseController < ::ErpApp::Desktop::BaseController
      
      end
    end #Ig
  end #Desktop
end #ErpApp

app/controllers/erp_app/desktop/website_controller.rb
#class WebsiteController < ApplicationController
#  def index
#  end
#end
module ErpApp
  module Desktop
    module ExampleApp
      class WebsiteController < ::ErpApp::Desktop::BaseController
      def index
	end
      end
    end #ExampleApp
  end #Desktop
end #ErpApp

app/controllers/erp_app/mobile/example_mobile_app/base_controller.rb
module ErpApp
	module Mobile
    module ExampleMobileApp
      class BaseController < ::ErpApp::Mobile::BaseController

        def index
          render :json => {:success => true, :message => 'Hello World'}
        end

      end #BaseController
    end #ExampleMobileApp
  end #Mobile
end #ErpApp

app/controllers/erp_app/organizer/example_organizer_app/base_controller.rb
module ErpApp
  module Organizer
    module ExampleOrganizerApp
      class BaseController < ::ErpApp::Organizer::BaseController

        def menu
          render :json => [{:text => 'Menu Item', :leaf => true, :iconCls => 'icon-tasks', :applicationCardId => "example_organizer_app_example_panel"}]
        end

      end #BaseController
    end #ExampleOrganizerApp
  end #Organizer
end #ErpApp

app/controllers/erp_app/organizer/ig_org/base_controller.rb
module ErpApp
  module Organizer
    module IgOrg
      class BaseController < ::ErpApp::Organizer::BaseController

        def menu
          render :json => [{:text => 'Menu Item', :leaf => true, :iconCls => 'icon-igorg', :applicationCardId => "ig_org_example_panel"}]
        end

      end #BaseController
    end #IgOrg
  end #Organizer
end #ErpApp

app/controllers/test_controller.rb
class TestController < ApplicationController
  def index
  end
end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController

  # GET /websites
  # GET /websites.json
  def index
    @websites = Website.all

    respond_to do |format|
      format.html  # index.html.erb
      format.json  { render :json => @websites }
    end
  end

# GET /websites/1
# GET /websites/1.json
  def show
    @website = Website.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @website }
    end
  end

  # GET /websites/new
  # GET /websites/new.json
  def new
   @website = Website.new
   respond_to do |format|
     format.html  # new.html.erb
     format.json  { render :json => @website }
   end
  end

  # Website /websites
  # Website /websites.json
  def create
  @website = Website.new(params[:website])
  #@website.save
  #redirect_to @website
  respond_to do |format|
    if @website.save
      format.html { redirect_to @website, notice: 'Website was successfully created.' }
      format.json { render json: @website, status: :created, location: @website }
    else
      format.html { render action: "new" }
      format.json { render json: @website.errors, status: :unprocessable_entity }
    end
  end
  end


  # GET /websites/1/edit
  def edit
    @website = Website.find(params[:id])
  end

  # PUT /websites/1
  # PUT /websites/1.json
  def update
    @website = Website.find(params[:id])

    respond_to do |format|
      if @website.update_attributes(params[:website])
        format.html  { redirect_to(@website,
                                   :notice => 'Website was successfully updated.') }
        format.json  { head :no_content }
      else
        format.html  { render :action => "edit" }
        format.json  { render :json => @website.errors,
                              :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /websites/1
  # DELETE /websites/1.json
  def destroy
    @website = Website.find(params[:id])
    @website.destroy

    respond_to do |format|
      format.html { redirect_to websites_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/website_helper.rb
module WebsiteHelper
end

app/helpers/websites_helper.rb
module WebsitesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<<<<<<< HEAD
  <title>Truenorth</title>
=======
  <title>IgSol</title>
>>>>>>> 0dbaabf22e79391f5b198e651d14e0b39b4c737e
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<<<<<<< HEAD

<%= yield %>

=======
<div id="main">
<div id="header">
<%= render 'header' %>
</div>
<div id="site_content">
<div id="content">
<%= yield %>
</div>
</div>

<%= render 'footer' %>
</div>
>>>>>>> 0dbaabf22e79391f5b198e651d14e0b39b4c737e
</body>
</html>

app/views/websites/_footer.html.erb
<div id="footer">
    Powered By <a href="http://development.compassagile.com">CompassAE</a>
</div>

app/views/websites/_form.html.erb
<%= form_for(@website) do |f| %>
    <% if @website.errors.any? %>
        <div id="errorExplanation">
          <h2><%= pluralize(@website.errors.count, "error") %> prohibited
            this website from being saved:</h2>
          <ul>
            <% @website.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :subtitle %><br />
      <%= f.text_field :subtitle %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/websites/_header.html.erb
<div>
  <div id="logo">
      <div id="logo_text">
        <h1><a href="/">TrueNorth Solutions</a></h1>
        <h2>Delivering Enterprises</h2>
      </div>
  </div>
</div>

app/views/websites/edit.html.erb
<h1>Editing Website</h1>

<%= render 'form' %>

<div id="nav">
    <%= link_to 'Show', @website %> |<%= link_to 'Back', websites_path %>
</div>

app/views/websites/index.html.erb
<h1>Listing Websites</h1>
<table>
  <tr>
    <th>Name</th>
    <th>Title</th>
    <th>Subtitle</th>
    <th colspan="3">Actions</th>
    </tr>

  <% @websites.each do |website| %>
      <tr>
        <td><%= website.name %></td>
        <td><%= website.title %></td>
        <td><%= website.subtitle %></td>
        <td><%= link_to 'Show', website %></td>
        <td><%= link_to 'Edit', edit_website_path(website) %></td>
        <td><%= link_to 'Destroy', website, :confirm => 'Are you sure?',
                        :method => :delete %></td>
      </tr>
  <% end %>
</table>

<div id="nav">
    <%= link_to 'New Website', new_website_path %>
</div>

app/views/websites/new.html.erb
<h1>New Website</h1>

<%= render 'form' %>
<div id="nav">
    <%= link_to 'Back', websites_path %>
</div>

app/views/websites/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @website.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @website.title %>
</p>

<p>
  <strong>Subtitle:</strong>
  <%= @website.subtitle %>
</p>


<%= link_to 'Back', websites_path %>